const data = [
   {
     title: "Internal Integration Planner",
     company: "Bauch, Schuppe and Schulist Co",
     img: "/img/jobs/joblogo.png",
     salary: "$280000-$320000",
     experience:"5",
     jobType: "Full-time",
     location: "New York, USA",
     industry: "IT & Software",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
     
   },
   {
     title: "Software Development Engineer",
     company: "Tech Innovations Ltd.",
     img: "/img/jobs/joblogo.png",
     salary: "$100000-$130000",
     experience:"4",
     jobType: "Full-time",
     location: "San Francisco, USA",
     industry: "IT & Software",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Marketing Strategist",
     company: "Growth Solutions Inc.",
     img: "/img/jobs/joblogo.png",
     salary: "$75000-$90000",
     experience:"5",
     jobType: "Part-time",
     location: "Chicago, USA",
     industry: "Marketing & Media",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "UI/UX Designer",
     company: "Pixel Perfect Studios",
     img: "/img/jobs/joblogo.png",
     salary: "$$85000-$$105000",
     experience:"2",
     jobType: "Remote",
     location: "Los Angeles, USA",
     industry: "Media & Design",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Senior Data Analyst",
     company: "Data Insights Corp.",
     img: "/img/jobs/joblogo.png",
     salary: "$95000-$$115000",
     jobType: "Full-time",
     location: "Boston, USA",
     industry: "Financial Services",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Project Manager",
     company: "Agile Project Solutions",
     img: "/img/jobs/joblogo.png",
     salary: "$$110000-130000",
     jobType: "Hybrid",
     location: "Austin, USA",
     industry: "Construction",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Cloud Solutions Architect",
     company: "SkyTech Cloud Services",
     img: "/img/jobs/joblogo.png",
     salary: "120000-$140000",
     jobType: "Full-time",
     location: "Seattle, USA",
     industry: "IT & Software",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Financial Advisor",
     company: "WealthWise Consultancy",
     img: "/img/jobs/joblogo.png",
     salary: "70000-$95000",
     jobType: "Part-time",
     location: "New York, USA",
     industry: "Financial Services",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "HR Business Partner",
     company: "People First HR",
     img: "/img/jobs/joblogo.png",
     salary: "$40000-100000",
     jobType: "Full-time",
     location: "San Diego, USA",
     industry: "Human Resources",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Cyber Security Engineer",
     company: "SecureNet Technologies",
     img: "/img/jobs/joblogo.png",
     salary: "$110000-$140000",
     jobType: "Remote",
     location: "Denver, USA",
     industry: "IT & Software",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Network Administrator",
     company: "FastConnect Networks",
     img: "/img/jobs/joblogo.png",
     salary: "$85000-$105000",
     jobType: "Full-time",
     location: "Dallas, USA",
     industry: "IT & Software",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Customer Support Manager",
     company: "ClientCare Solutions",
     img: "/img/jobs/joblogo.png",
     salary: "$60000-$80000",
     jobType: "Hybrid",
     location: "Miami, USA",
     industry: "Customer Service",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "E-commerce Specialist",
     company: "ShopEase Online",
     img: "/img/jobs/joblogo.png",
     salary: "70000-$95000",
     jobType: "Full-time",
     location: "Chicago, USA",
     industry: "E-commerce",
     Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Legal Consultant",
     company: "Lex Partners LLP",
     img: "/img/jobs/joblogo.png",
     salary: "120000-150000",
     jobType: "Contract",
     location: "New York, USA",
     industry: "Legal Services",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Product Owner",
     company: "InnovateX Technologies",
     img: "/img/jobs/joblogo.png",
     salary: "$105000-125000",
     jobType: "Full-time",
     location: "Boston, USA",
     industry: "IT & Software",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "AI & Machine Learning Engineer",
     company: "DeepMind Systems",
     img: "/img/jobs/joblogo.png",
     salary: "130000-1$60000",
     jobType: "Remote",
     location: "Anywhere",
     industry: "AI & Machine Learning",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "DevOps Engineer",
     company: "CodeFlow Solutions",
     img: "/img/jobs/joblogo.png",
     salary: "$115000-$135000",
     jobType: "Full-time",
     location: "San Francisco, USA",
     industry: "IT & Software",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Social Media Manager",
     company: "TrendBoost Marketing",
     img: "/img/jobs/joblogo.png",
     salary: "$60000-$$85000",
     jobType: "Part-time",
     location: "Los Angeles, USA",
     industry: "Marketing & Media",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Content Marketing Specialist",
     company: "Creative Content Agency",
     img: "/img/jobs/joblogo.png",
     salary: "65000-90000",
     jobType: "Full-time",
     location: "New York, USA",
     industry: "Marketing & Media",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   },
   {
     title: "Operations Coordinator",
     company: "BizOps Management",
     img: "/img/jobs/joblogo.png",
     salary: "75000-$95000",
     jobType: "Full-time",
     location: "Seattle, USA",
     industry: "Business Operations",
      Description:["Nunc sed a nisl purus. Nibh dis faucibus proin lacus tristique. Sit congue non vitae odio sit erat in. Felis eu ultrices a sed massa. Commodo fringilla sed tempor risus laoreet ultricies ipsum. Habitasse morbi faucibus in iaculis lectus. Nisi enim feugiat enim volutpat. Sem quis viverra viverra odio mauris nunc.","Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augue lorem amet adipiscing cursus fames mauris. Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta eget blandit euismod sem nunc. Tortor gravida amet amet sapien mauris massa.Tortor varius nam maecenas duis blandit elit sit sit. Ante mauris morbi diam habitant donec."],
     Responsibilities:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare. Cras facilisis dignissim augu","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae. Quisque tincidunt metus lectus porta"],
     skills:["Et nunc ut tempus duis nisl sed massa. Ornare varius faucibus nisi vitae vitae cras ornare.","Ornare varius faucibus nisi vitae vitae cras ornare","Tortor amet porta proin in. Orci imperdiet nisi dignissim pellentesque morbi vitae"],
     tags:["Full time","ecoomerce","newYork","location"]
   }
 ];
 
 export default data;
 

 